- name: Stop Integration Server
  ansible.builtin.systemd:
    state: stopped
    name: is.service
  when: inventory_hostname in groups['esb-dev-terracota-is']
  tags: stop

- name: Stop My Webmethods Server
  ansible.builtin.systemd:
    state: stopped
    name: mws.service
  when: inventory_hostname in groups['esb-dev-mws']
  tags: stop

- name: Stop Terracotta
  ansible.builtin.systemd:
    state: stopped
    name: terracotta.service
  when: inventory_hostname in groups['esb-dev-terracota-is']
  tags: stop

- name: Stop Universal Messaging Server
  ansible.builtin.systemd:
    state: stopped
    name: um.service
  when: inventory_hostname in groups['esb-dev-ums']
  tags: stop

- name: Stop Oracle Database WEBMDDB1
  command: sudo -iu oracle /opt/oracle/19.3.0/bin/srvctl stop database -d webmddb1
  when: inventory_hostname in groups['esb-dev-database']
  tags: stop

- name: Stop Oracle Database ASM
  command: sudo /opt/grid/19.3.0/bin/crsctl stop has
  when: inventory_hostname in groups['esb-dev-database']
  tags: stop

