- name: Start Cassandra service
  ansible.builtin.systemd:
    state: started
    name: apigee-cassandra.service
  when: inventory_hostname in groups['apigee-uat-zookeper-cassandra']
  tags: start

- name: Start OpenLDAP service
  ansible.builtin.systemd:
    state: started
    name: apigee-openldap.service
  when: inventory_hostname in groups['apigee-uat-openldap']
  tags: start

- name: Start Portal Database service
  ansible.builtin.systemd:
    state: started
    name: apigee-postgresql.service
  when: inventory_hostname in groups['apigee-uat-portaldb']
  tags: start

- name: Start QPID service 
  ansible.builtin.systemd:
    state: started
    name: apigee-qpidd.service
  when: inventory_hostname in groups['apigee-uat-qpid']
  tags: start

- name: Start Zookeper service
  ansible.builtin.systemd:
    state: started
    name: apigee-zookeeper.service
  when: inventory_hostname in groups['apigee-uat-zookeper-cassandra']
  tags: start

- name: Start Management Server service
  ansible.builtin.systemd:
    state: started
    name: edge-management-server.service
  when: inventory_hostname in groups['apigee-uat-man-edge']
  tags: start

- name: Start Message Processor service
  ansible.builtin.systemd:
    state: started
    name: edge-message-processor.service
  when: inventory_hostname in groups['apigee-uat-router-msg']
  tags: start

- name: Start Postgres service
  ansible.builtin.systemd:
    state: started
    name: edge-postgres-server.service
  when: inventory_hostname in groups['apigee-uat-postgres']
  tags: start

- name: Start QIPD Server service
  ansible.builtin.systemd:
    state: started
    name: edge-qpid-server.service
  when: inventory_hostname in groups['apigee-uat-qpid']
  tags: start

- name: Start Router service 
  ansible.builtin.systemd:
    state: started
    name: edge-router.service
  when: inventory_hostname in groups['apigee-uat-router-msg']
  tags: start

- name: Start Edge UI service  
  ansible.builtin.systemd:
    state: started
    name: edge-ui.service
  when: inventory_hostname in groups['apigee-uat-man-edge']
  tags: start

- name: Start Portal service 
  command: /opt/apigee/apigee-service/bin/apigee-service apigee-drupal-devportal start
  when: inventory_hostname in groups['apigee-uat-portal-lb']
  tags: start

- name: Start Portal LoadBalance service 
  ansible.builtin.systemd:
    state: started
    name: apigee-lb.service
  when: inventory_hostname in groups['apigee-uat-portal-lb']
  tags: start


