- name: Check if there are any database process running
  shell: /opt/grid/19.3.0/bin/crsctl status res | grep -wns asm -A 1
  when: inventory_hostname in groups['esb-uat-database']
  register: databasename
  tags: start

- name: debug 
  ansible.builtin.debug:
    msg: "process running"
  when: ('"asm_pmon_+ASM1" not in databasename')

- name: Start Oracle Database ASM
  ignore_errors: true
  command: sudo /opt/grid/19.3.0/bin/crsctl start crs -wait
  when: inventory_hostname in groups['esb-uat-database']
  tags: start

- name: Start Oracle Database WEBMDDB1
  ignore_errors: true
  command: sudo -iu oracle /opt/oracle/19.3.0/bin/srvctl start database -d WEBMUDB
  when: inventory_hostname in groups['esb-uat-database']
  tags: start

- name: Start Universal Messaging Server
  ansible.builtin.systemd:
    state: started
    name: um.service
  when: inventory_hostname in groups['esb-uat-ums']
  tags: start

- name: Start Terracotta
  ansible.builtin.systemd:
    state: started
    name: terracotta.service
  when: inventory_hostname in groups['esb-uat-terracota-is']
  tags: start

- name: Start Integration Server
  ansible.builtin.systemd:
    state: started
    name: is.service
  when: inventory_hostname in groups['esb-uat-terracota-is']
  tags: start

- name: Start My Webmethods Server
  ansible.builtin.systemd:
    state: started
    name: mws.service
  when: inventory_hostname in groups['esb-uat-mws']
  tags: start





