- name: Stop Integration Server
  ansible.builtin.systemd:
    state: stopped
    name: is.service
  when: inventory_hostname in groups['esb-uat-terracota-is']
  tags: stop

- name: Stop My Webmethods Server
  ansible.builtin.systemd:
    state: stopped
    name: mws.service
  when: inventory_hostname in groups['esb-uat-mws']
  tags: stop

- name: Stop Terracotta
  ansible.builtin.systemd:
    state: stopped
    name: terracotta.service
  when: inventory_hostname in groups['esb-uat-terracota-is']
  tags: stop

- name: Stop Universal Messaging Server
  ansible.builtin.systemd:
    state: stopped
    name: um.service
  when: inventory_hostname in groups['esb-uat-ums']
  tags: stop

- name: Stop Oracle Database WEBMDDB1
  command: sudo -iu oracle /opt/oracle/19.3.0/bin/srvctl stop database -d WEBMUDB
  when: inventory_hostname in groups['esb-uat-database2']
  tags: stop

- name: Stop Oracle Database ASM
  command: sudo /opt/grid/19.3.0/bin/crsctl stop crs
  when: inventory_hostname in groups['esb-uat-database1']
  tags: stop

